language: python
python:
  - "2.7"
  - "3.6"

sudo: required

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create user travis;' -U postgres

# command to install dependencies
install: make pipupgrade

# command to run tests
script: make tox
