language: python
python:
  - "2.7"
  - "3.6"

sudo: required

dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.6"

# command to install dependencies
install: make pipupgrade

# command to run tests
script: make tox
