language: python
python:
  - "2.7"
  - "3.6"

sudo: required

dist: trusty

services:
  - postgresql

addons:
  postgresql: "9.6"
before_script:
  - bash scripts/travis/install-postgres-10.sh

# command to install dependencies
install: make pip

# command to run tests
script: make test
